-- =========================================================
-- ROMUEL APPS V9 : STATISTIQUES DE TELECHARGEMENT
-- Exécuter UNE SEULE FOIS dans Supabase > SQL Editor
-- =========================================================

create table if not exists public.download_events (
  id bigint generated by default as identity primary key,
  app_id text not null,
  version text,
  user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.download_events enable row level security;

-- Un visiteur (connecté ou non) peut enregistrer un clic de téléchargement.
drop policy if exists "Enregistrer telechargement" on public.download_events;
create policy "Enregistrer telechargement"
on public.download_events
for insert
to anon, authenticated
with check (
  user_id is null
  or auth.uid() = user_id
);

-- Seul un administrateur peut consulter les statistiques brutes.
drop policy if exists "Admin lit telechargements" on public.download_events;
create policy "Admin lit telechargements"
on public.download_events
for select
to authenticated
using (public.is_admin());

create index if not exists download_events_app_id_idx
on public.download_events(app_id);

create index if not exists download_events_created_at_idx
on public.download_events(created_at desc);

-- L'admin peut lire tous les favoris pour les statistiques futures.
drop policy if exists "Admin lit favoris" on public.favorites;
create policy "Admin lit favoris"
on public.favorites
for select
to authenticated
using (public.is_admin());
